services:
  app:
    container_name: ontv-front
    image: ontv/frontend
    hostname: ontv-front
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      target: development
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000