services:
  app:
    container_name: ontv-front-prod
    image: ontv/frontend-prod
    hostname: ontv-front
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
      target: production
    ports:
      - 3000:3000