# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags: ["dev-*.*.*"]

env:
  IMAGE_NAME: c0mm4nder/onnyfront
  ARVAN_IMAGE_NAME: docker.arvancloud.ir/c0mm4nder/onnyfront
  CONTAINER_NAME: ontv-front-dev
  REGISTRY : registry-860220ff8e-nehzat.apps.ir-thr-ba1.arvancaas.ir

jobs:
  Stage1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Get version
        run: echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build image ontv
        run: docker build -f .docker/Dockerfile.dev -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }} --target production .

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME_REG }}
          password: ${{ secrets.DOCKER_PASSWORD_REG }}

      - name: Push ontv to Dockerhub
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}

  Stage2:
    needs: Stage1
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Publish ontv to ArvanCloud PaaS
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/${{ env.CONTAINER_NAME }} ${{ env.CONTAINER_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
