# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags: ["prod-*.*.*"]

env:
  IMAGE_NAME: c0mm4nder/onnyfront
  ARVAN_IMAGE_NAME: docker.arvancloud.ir/c0mm4nder/onnyfront
  CONTAINER_NAME: ontv-front-prod
  REGISTRY : registry-860220ff8e-nehzat.apps.ir-thr-ba1.arvancaas.ir

jobs:
  Stage1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Get version
        run: echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build image ontv
        run: docker build -f .docker/Dockerfile.prod -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }} --target production .

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME_REG }}
          password: ${{ secrets.DOCKER_PASSWORD_REG }}

      - name: Push ontv to Dockerhub
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}